spring.application.name=WeatherAPP

# H2 Database
spring.datasource.url=jdbc:h2:mem:appdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Spring Cache
spring.cache.type=simple
# Redis Cache
#spring.cache.type=redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.cache.cache-names=weather

# Server
server.port=8080